windows-agent/internal/config/config.go
windows-agent/internal/config/config_test.go

I want cloud-init & landscape to be pinged by the config every time something changes. However, I don't want these two utilities to be dependencies of config. If anything, I want the dependency the other way around! Cloud-init and Landscape should import config.
So I must somehow call these utilities from the config without importing them. My solution: callbacks. Any utility can now wait on config changes by using:
```go
conf.Notify(func() {
fmt.Println("Hello, world")
})
```
and this function will be called every time the config is changed (via GUI, registry, or any future methods).
This is used in Landscape #515 and Cloud-init #506.

feat(config): Implement notification system for Config

---

common/consts.go
end-to-end/main_test.go
end-to-end/utils_test.go
gui/packages/ubuntupro/integration_test/ubuntu_pro_for_wsl_test.dart
gui/packages/ubuntupro/lib/constants.dart
gui/packages/ubuntupro/lib/pages/startup/agent_monitor.dart
gui/packages/ubuntupro/lib/pages/startup/startup_model.dart
gui/packages/ubuntupro/test/core/agent_api_paths_part4_test.dart
gui/packages/ubuntupro/test/core/agent_api_paths_test.dart
gui/packages/ubuntupro/test/startup/agent_monitor_test.dart
windows-agent/cmd/ubuntu-pro-agent/agent/agent.go
windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
windows-agent/cmd/ubuntu-pro-agent/agent/export_test.go
windows-agent/internal/daemon/daemon.go
windows-agent/internal/daemon/daemon_test.go
windows-agent/internal/proservices/proservices.go
windows-agent/internal/proservices/proservices_test.go
wsl-pro-service/go.mod
wsl-pro-service/go.sum
wsl-pro-service/internal/controlstream/controlstream.go
wsl-pro-service/internal/testutils/mock_executables.go

We'll soon have more "public" files (aka non restricted to the agent) due to the need to store cloud-init files. We'll put all these files inside `$env:UserProfile/.ubuntupro` to avoid filling the home directory with our garbage.
This PR does two things:
1. Refactor directory management in the agent to clarify this public vs. private distinction.
2. Move the address file into the public dir.
3. (bonus) fix a lot of things that broke as a consequence.
---
UDENG-2222

maint: Create ubuntupro dir and move address file inside of it

---

wsl-pro-service/internal/daemon/daemon_test.go

Some tests failed in the launchpad runner. See here: https://objectstorage.prodstack5.canonical.com/swift/v1/AUTH_0f9aae918d5b4744bf7b827671c86842/autopkgtest-noble/noble/armhf/w/wsl-pro-service/20240202_051125_c3828@/log.gz
They are all related to require.Eventually assertions, so I increased their timeouts. This may worsen performance when tests fail, but the happy path remains just as fast.
Related to #535.
---
UDENG-2228

fix(wsl-pro-service): Increase a couple of timeouts in the tests

---

go.work.sum
mocks/landscape/landscapemockservice/landscape_mock_service.go
windows-agent/internal/proservices/landscape/connection.go
windows-agent/internal/proservices/landscape/controller.go
windows-agent/internal/proservices/landscape/executor_test.go
windows-agent/internal/proservices/landscape/interfaces.go
windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/landscape/service.go
windows-agent/internal/proservices/landscape/utils.go
windows-agent/internal/proservices/proservices.go

It just doesn't work.
This PR does multiple things around reconnection:
1. Fix the signal so that the Controller can ask Landscape to reconnect. (UDENG-2195)
2. Improve the way the connection is monitored, and restart it if it fails.
3. Implement a notification system in Config. Use this to reconnect to Landscape every time the relevant config is changed (UDENG-2196).

fix(landscape): Landscape reconnect signal does nothing

---

gui/packages/ubuntupro/end_to_end/end_to_end_test.dart
gui/packages/ubuntupro/integration_test/ubuntu_pro_for_wsl_test.dart
gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/subscription_status/subscribe_now_page.dart
gui/packages/ubuntupro/lib/pages/subscription_status/subscribe_now_widgets.dart
gui/packages/ubuntupro/test/pages/subscription_status/subscribe_now_page_test.dart

The proposed changes for the Ubuntu Pro Flutter GUI design have differing strings, so this PR changes those strings and also the keys associated with them so they make more sense. These are all cosmetic changes and do not alter the functionality of the application.
*Force push was to correct the email used for the sake of CLA signing*
---
UDENG-1986

fix(gui-ubuntupro): Update GUI strings to proprosed desgin

---

docs/.custom_wordlist.txt
docs/reference/landscape.md

I've added some missing info. Feel free to accept/reject as you see fit, but the port number on the URL should be accepted. AFAIK, adding the port number is expected to be temporary. I'll keep your docs updated if/when that changes.
I didn't want to delete the information you had already regarding the Agent keys, but I was a bit confused by that section and what users should do with the other keys. If you want to go over it some time, feel free to MM me or schedule a meeting. I know your docs are under construction though so I think it's fine for now too :smiley: 
Also, here's the link to the Landscape Docs for registering a WSL host, if that's helpful: https://ubuntu.com/landscape/docs/register-wsl-hosts-to-landscape

docs: Added LandscapeConfig keys

---

windows-agent/internal/config/config.go
windows-agent/internal/config/config_marshal.go
windows-agent/internal/config/config_test.go
windows-agent/internal/proservices/landscape/executor_test.go
windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/proservices.go
windows-agent/internal/proservices/ui/ui_test.go

This prevents using it during the process teardown. Particulary relevant to async work like the observers.
Using the config during teardown is, I believe, the reason why this test fails:
https://github.com/canonical/ubuntu-pro-for-wsl/actions/runs/7813886532/job/21314974693?pr=506#step:8:38
I think cloud-init is writing `agent.yaml` at the same time as the test teardown in trying to remove its temp directory. On Windows, you cannot remove an open file.

fix(windows-agent): Add Stop function to Config

---

windows-agent/internal/config/config.go

This commit fixes a deadlock between config.Stop and any config notifaction callback that uses a config Mutex.
Scenario:
1. A config notification is triggered: the waitgroup count is increased by one and a single callback is called and starts executing. Waitgroup count decrease is deferred until the callback returns.
2. config.Stop is called, the config's ctx is cancelled but it is too late: the callback has already started. Then the config mutex is locked and it waits on the config waitgroup. This blocks until the waitgroup count reached 0.
3. during its execution, the callback calls some getter in the config. The mutex is already locked, so the getter cannot proceed, hence it cannot return. The deferred waitgroup count decrease never happens.
This is a deadlock! config.Stop is waiting …

fix(windows-agent): Fix deadlock in config Stop

---

gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/subscription_status/subscription_status_page.dart
gui/packages/ubuntupro/lib/pages/subscription_status/subscription_status_widgets.dart
gui/packages/ubuntupro/lib/pages/widgets/page_widgets.dart
gui/packages/ubuntupro/pubspec.lock
gui/packages/ubuntupro/pubspec.yaml

This PR redesigns the subscription status page to be more consistent with the designs for Provisioning. It includes having clickable text links, centering the title, text, and buttons, and outlining the text with a green background box.
This required changing the flow of the main layout and adding a `centered` option, so it may be more changes than you might suspect. This same layout will likely be used for the Landscape status page as well.
**New design**
**Old design (but with color changes and clickable link)**
---
UDENG-1786

fix: Align subscription status page with Provisioning design

---

mocks/landscape/landscapemockservice/landscape_mock_service.go
windows-agent/internal/proservices/landscape/controller.go
windows-agent/internal/proservices/landscape/interfaces.go
windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/landscape/service.go

The "if error -> increase wait" logic did not work.
It now does work, and we also consider short-lived connections as errors (to avoid spamming 1-second connections that the server rejects for whatever reason, or spamming with flaky connections, etc).
This also fixes the recently flaky Landscape tests.
---
UDENG-2261

fix(Landscape): fix bad time staircase

---

codecov.yml

Should allow CI to be happier with racy tests
Until we figure out the source of fluctuations I guess.
All cases in CI which we could forgive coverage drop reports were well under 0.80%, so 1% seems not too tight.
Let see how this goes.
Ref: 
- https://docs.codecov.com/docs/commit-status
- https://docs.codecov.com/docs/codecov-yaml

maint(ci): Allows that one percent coverage reduction

---

windows-agent/cmd/ubuntu-pro-agent/main.go

This formatter is for consoles so it looks ugly in logfiles. The default logger produces structured logging so it works well enough, but I removed the quotes because windows\\\\paths\\\\are\\\\annoying\\\\to\\\\copy\\\\and\\\\paste.
Before:
```
======= STARTUP =======
[36mINFO[0m Time: 2024-02-23T15:01:40+01:00              
[36mINFO[0m Version: Dev                                 
[37mDEBUG[0m Debug mode is enabled                        
[37mDEBUG[0m Agent public directory: C:\Users\edu19\.ubuntupro 
[37mDEBUG[0m Agent private directory: C:\Users\edu19\AppData\Local\Ubuntu Pro 
```
After
```
======= STARTUP =======
time=2024-02-23T17:21:45+01:00 level=info msg=Version: Dev
time=2024-02-23T17:21:45+01:00 level=debug msg=Debug mode is enabled
time=2024-02-23T17:21:45+01:00 …
```

fix(windows-agent): Use the almost-default logrus formatter

---

msix/UbuntuProForWSL/Package.appxmanifest

By deploying firewall rules for all network profiles. I had success with this testing in VMs. I'd like to have others testing the build to make sure the firewall popups won't show up before merging.

fix(msix): Attempt to prevent firewall popus

---

windows-agent/internal/proservices/landscape/landscape_test.go

The diff is quite subtle, here is the explanation. This part of the test does the following:
1. Wait until we connect to the Landscape server.
2. Stop the server and detect the disconnection.
We validate that we connected to the server by querying the client -> client.Connected().
Step 2 has three sub-steps:
- 2.1 Ensure we are connected
- 2.2 Stop the server
- 2.3 Wait for disconnection
We perforn the step 2.1 by querying the server ->
server.IsConnected(clientUID)
There is a race between 1. and 2.1! There is a brief window of time where the gRPC connection has been made, but the server has not yet added the client to its internal database. Hence, check 1. succeeds but check 2.1 fails (as the UID is not yet recognized).
Changing step 1. to query the server is the easiest fix.

fix(windows-agent): Fix race in Landscape tests

---

msix/UbuntuProForWSL/Package.appxmanifest

inside the .appxmanifest file.
ref: https://github.com/canonical/ubuntu-pro-for-wsl/pull/600#issuecomment-1964206066 and https://github.com/canonical/ubuntu-pro-for-wsl/actions/runs/8049768246/job/21984022791?pr=599#step:9:257

fix(msix): Port numbers must be quoted

---

end-to-end/landscape_utils_test.go
windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/landscape/utils.go

Landscape quick setup for now at least is not talking to the agent over TLS. The team was advised and they are working to enable such feature. In the meanwhile let's use insecure credentials on the connection to Landscape. I'm doing this in a ugly but easy to revert way.

maint(windows-agent): No TLS from agent to Landscape

---

msix/ubuntu-pro-agent-launcher/main.cpp

I played with this in different scenarios and ended up with the most obvious one: doing the call to register the application restart the earliest possible in `main`. I'd like to defer that registration to the last moment possible (when the message `WM_QUERYENDSESSION` arrives to the queue), but that would only work if I create a window, something we don't do in the agent, which is a true console application, nor in the agent launcher, which is a fake window app, since it does not create a window.
This does what it promisses: once a build containing this patch is asked to close to install updates, the OS is tasked to restart the new version of the agent launcher (and consequently the agent). Notice that the restart is ignored if the app gets closed due hang, crash or reboot …

fix(msix): Restart automatically after receiving updates

---

wsl-pro-service/internal/controlstream/controlstream.go

Thanks @iosifache for noticing!
Co-authored-by: Didier Roche-Tolomelli <didrocks@ubuntu.com>

fix(wsl-pro-service): Fix bug where IPv6 addresses where badly concatenated with port

---

windows-agent/internal/ubuntupro/ubuntupro_test.go

We were leaking the distro task processing. This caused a race in the removal of the distro's working dir.
See race here: https://github.com/canonical/ubuntu-pro-for-wsl/actions/runs/8097649091/job/22129174184#step:7:72

fix(windows-agent): Fix race in ubuntupro tests

---

windows-agent/go.mod
windows-agent/go.sum

We were currently pinned at a four-month-old commit. The only changes are dependabot things, but those may contain security fixes

deps(windows-agent): Update GoWSL dependency

---

docs/reference/landscape.md

Updated to match the new example in the [Landscape Docs - How to configure Ubuntu Pro for WSL](https://ubuntu.com/landscape/docs/register-wsl-hosts-to-landscape).
Changes:
- `[host]` `url` shouldn't be sent with `https://`
- `ssl_public_key` must be included in the `[client]` section with the recent Landscape change for gRPC messages to use https

Update example `LandscapeConfig`

---

gui/packages/ubuntupro/integration_test/ubuntu_pro_for_wsl_test.dart
gui/packages/ubuntupro/lib/app.dart
gui/packages/ubuntupro/lib/pages/startup/startup_page.dart
gui/packages/ubuntupro/lib/pages/subscription_status/subscription_status_page.dart
gui/packages/ubuntupro/test/pages/subscription_status/subscription_status_page_test.dart

For users it looks like the app forgotten the Pro token previously supplied. The current state is always starting in the subscribe now page. When refactoring the app code, we mistakenly placed the call to get the current subscription status in the last screen, it should be on the first.
Added an integration test to assert that behavior.
Also, notice the usage of `Wizard.of(context).replace()` instead of `.next()` or `.jump()`. It has the benefit of removing the current page from the navigator, thus allowing the `SubscriptionStatusPage` to consider itself the only one if the apps starts with a pre-existing subscription as well as prevents undesired back navigations (such as going back from the `SubscribeNowPage` to the `SubscriptionStatusPage` or the `StartupPage`).

fix(gui): Regression: not checking subscription status on startup

---

windows-agent/internal/proservices/landscape/connection.go
windows-agent/internal/proservices/landscape/landscape_test.go

The connection dropping should not stop a distro registration, for instance.
And for the server to know that a command worked, we should ping them when it has completed.
---
UDENG-2422
UDENG-2425

feat(Landscape): Do not cancel commands in progress, and ping the server back on completion

---

end-to-end/utils_test.go

We moved the logs and forgot that the E2E tests look for them!

fix(end-to-end): Fix log path in E2E testing

---

gui/packages/ubuntupro/integration_test/ubuntu_pro_for_wsl_test.dart
windows-agent/internal/config/config.go
windows-agent/internal/config/config_test.go

This function is called when the UI reports a new Landscape config
---
UDENG-2421

feat(windows-agent): Notify landscape when SetUserLandscapeConfig is used

---

end-to-end/landscape_utils_test.go
windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/landscape/utils.go

This reverts commit 1b7275d345b1bf7125b17bb1fd0f9b3190a424c6, reversing changes made to 63bb25988bcc9e92f916f525a950f59f449d383e.
Merge once @wck0 pings us.
---
UDENG-2424

maint(windows-agent): Revert "No TLS from agent to Landscape (#601)"

---

gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_widgets.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_page_test.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_widgets_test.dart

Team's feedback was that the button was not looking like a Yaru styled button. It was, but a `TextButton` which is a low emphasis component. Upon discussion, we settled with the higher emphasis `ElevatedButton`, which is even higher in Yaru.
So this removes any further styling, convert the button to `ElevatedButton` and detaches it from the text input field. No functionality changes, yet some tests required updates in how they find that button.
UDENG-2376

fix(gui): Promotes the "Confirm" button

---

windows-agent/internal/proservices/ui/ui.go
windows-agent/internal/tasks/pro_attachment.go

Previously, the pro token was being logged fully when applied. This PR obfuscates that token so that only the first and last 2 characters are visible.
---
UDENG-2354

feat(windows-agent): Obfuscate pro token when logged

---

wsl-pro-service/internal/system/landscape.go
wsl-pro-service/internal/system/pro.go
wsl-pro-service/internal/system/system.go

We were not printing Stderr when something failed, meaning that we lost most of the error message.

maint(wsl-pro-service): Better logging of subprocess errors in WSL-Pro-Service

---

wsl-pro-service/internal/controlstream/controlstream.go
wsl-pro-service/internal/controlstream/controlstream_test.go

The port in the address file can be negative which would cause errors down the line. We also want to avoid port 0 as that usually means "any port" in go land.
Closes #629 
UDENG-2426

fix(wsl-pro-service): Validate port read from the address file

---

windows-agent/internal/distros/worker/worker.go

Closes #674 
^ The test was not flaky but rather the behaviour!
---
UDENG-2457

fix(windows-agent): Fix clean-up of tasks when the distro is invalidated.

---

windows-agent/cmd/ubuntu-pro-agent/main.go
windows-agent/cmd/ubuntu-pro-agent/main_linux_test.go
windows-agent/cmd/ubuntu-pro-agent/main_test.go

This PR renames any existing log to `log.old` when the program starts, overwriting the file if it already exists. It also tests that if a log exists a log.old is successfully created.
---
UDENG-2355

fix(windows-agent): Truncate log files

---

wsl-pro-service/internal/system/backend.go
wsl-pro-service/internal/system/export_test.go
wsl-pro-service/internal/system/landscape.go
wsl-pro-service/internal/system/networking.go
wsl-pro-service/internal/system/pro.go
wsl-pro-service/internal/system/system.go
wsl-pro-service/internal/system/system_test.go
wsl-pro-service/internal/testutils/mock_executables.go

cmd.exe prints random stuff to stderr. When attempting to parse the output of `cmd.exe`, Stderr gets in the way and we fail.
Regression introduced in 373a97d
---
UDENG-2476

fix(wsl-pro-service): Don't break when processes print to Stderr

---

gui/packages/ubuntupro/lib/main.dart
gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_widgets.dart
gui/packages/ubuntupro/lib/pages/widgets/page_widgets.dart
gui/packages/ubuntupro/pubspec.lock
gui/packages/ubuntupro/pubspec.yaml

The community deprecated yaru_icons and yaru_widgets, merging them into yaru. So now we must only depend on yaru and remove the deprecated dependencies from our `pubspec.yaml`. Since the theme, icons and widgets are in the same package now, some imports need fixes.

maint(gui): Upgrade yaru, remove deprecated child packages and fixes imports.

---

common/go.mod
common/go.sum
end-to-end/go.mod
end-to-end/go.sum
tools/go.mod
tools/go.sum
windows-agent/go.mod
windows-agent/go.sum
windows-agent/internal/distros/distro/properties.go

This PR fixes a race where unregistering a distro at a very unfortunate time would cause a panic.
From [LBYL](https://docs.python.org/3.5/glossary.html#term-lbyl) to [EAFP](https://docs.python.org/3.5/glossary.html#term-eafp) 😃
---
UDENG-2385

fix(windows-agent): Avoid panic in distro properties

---

common/testutils/golden.go

This will make it clear this is scope for tests, so that we don’t mix with other potential env available. Also, have it as verb/action rather than passive form.
We are going to use this in other repos.

feat(tests): change golden files update flag

---

wsl-pro-service/debian/control

From v31, ubuntu-advantage-tools has been renamed to ubuntu-pro-client. The ubuntu-advantage-tools package name is now a transitional package. Noble currently has ubuntu-advantage-tools v31.

deps(wsl-pro-service): update the package name for ubuntu-advantage-tools

---

docs/dev/howto/02-install.md
docs/dev/howto/03-restart.md
docs/dev/howto/06-access-the-logs.md
docs/dev/howto/index.md
docs/dev/reference/07-windows-agent-command-line-reference.md
docs/dev/reference/08-wsl-pro-service-command-line-reference.md
docs/dev/reference/index.md
docs/howto/index.md
docs/howto/set-up-up4w.md
docs/index.md
docs/reference/index.md
docs/reference/landscape.md
docs/reference/landscape_client.md
docs/reference/ubuntu_pro.md
docs/reference/ubuntu_pro_client.md
docs/reference/up4w-windows_agent.md
docs/reference/up4w-wsl_pro_service.md
docs/reference/up4w.md

Touched up titles in Navigation to remove "How to" or to include just the abbreviation.
Restyled "Ubuntu Pro for WSL" everywhere *except for first occurrence on the website, in the home, and the install page) as just "UP4W".
Touched up See, See first, See more, See also style in all the docs
- See: used when we link to something else for the entire content of a point
- See also: used at the top of a HTG section to link to the immediately relevant reference
- See more: used in HTGs to link to reference bits used in the HTG or in Reference to link to external pages for more info
- See first: used in the UP4W Dev docs to link to the bits that the dev doc is adding to.
In the setup HTG, turned Prerequisites into a Check that you meet requirements section. Also touched up the content to …

docs: Improve style consistency everywhere, improve flow in setup prerequisites

---

end-to-end/manual_token_input_test.go
end-to-end/organization_token_test.go

sometimes pro attach is very slow

fix(end-to-end): Increase timeouts in pro attachment check

---

gui/packages/ubuntupro/lib/constants.dart
gui/packages/ubuntupro/lib/core/agent_api_paths.dart
gui/packages/ubuntupro/lib/core/agent_monitor.dart
gui/packages/ubuntupro/test/core/agent_api_paths_test.dart
windows-agent/internal/daemon/daemon.go
windows-agent/internal/daemon/daemon_test.go
windows-agent/internal/daemon/export_test.go
windows-agent/internal/daemon/networking_mock.go
windows-agent/internal/daemon/networking_windows.go

Up until now we listened to all interfaces, this of course exposed us to the outside world.
With this change, we stay in our network, and we hope we'll also avoid ugly Windows Defender firewall pop-ups.
You can get this address in Powershell with:
```
Get-NetIPAddress -InterfaceAlias 'vEthernet (WSL (Hyper-V firewall))' -AddressFamily "IPv4" | Select-Object -ExpandProperty IPAddress
```
I prefered to avoid unnecessary subprocessing, so we instead use the Win32 API:
https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses
---
UDENG-2320

feat(windows-agent): Daemon listens at the hyper-V adapter

---

wsl-pro-service/internal/system/backend.go
wsl-pro-service/internal/system/landscape.go
wsl-pro-service/internal/system/system.go
wsl-pro-service/internal/system/system_test.go
wsl-pro-service/internal/system/testdata/TestLandscapeEnable/error_when_the_landscape_user_does_not_exist/landscape.conf
wsl-pro-service/internal/testutils/mock_executables.go

The landscape group needs read-access to the /etc/landscape/client.conf file. However, we do not want any user to be able to read it as it may contain confidential details such as the registration key. The solution is to restrict its visibility to its owner and group, and to add it to landscape's group
Thanks @iosifache for spotting this vulnerability.
---
UDENG-2540

fix(landscape): Restrict landscape config file from 0604 to 0640

---

go.work.sum
windows-agent/cmd/ubuntu-pro-agent/agent/agent.go

When we call agent.Quit, we don't wait for the proServices to perform their cleanup. This means that the process can exit while the Landscape, registry watcher or database are in the middle of an operation.
This PR fixes this, somewhat: It guarantees to exit the process after proservices.Stop returns. We trust that the implementation of the teardown of these proservices is implemented properly (I gave it a quick glance and it seems to be the case).
This problem also affected tests, as the proServices could be writing to disk while t.Cleanup tries to delete the temp directory, causing a race and then a test error.
---
Example test failure due to this: https://github.com/canonical/ubuntu-pro-for-wsl/actions/runs/8436243216/job/23103334236?pr=702#step:7:63
Here, the proservices manager is …

fix(windows-agent): Avoid leaking proservices Manager on app teardown

---

windows-agent/cmd/ubuntu-pro-agent/agent/agent.go
windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
windows-agent/cmd/ubuntu-pro-agent/agent/clean.go
windows-agent/cmd/ubuntu-pro-agent/main.go
windows-agent/cmd/ubuntu-pro-agent/main_test.go

```
ubuntu-pro-agent.exe clean
```
This command removes directories `~/.ubuntupro` and `$LocalAppData\Ubuntu Pro`.
Eventually the MSIX uninstaller should call this command so as to clean up after itself. It's also useful for local testing.
---
UDENG-2231

feat: Implement clean verb for the agent

---

windows-agent/cmd/ubuntu-pro-agent/agent/agent.go
windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
windows-agent/cmd/ubuntu-pro-agent/agent/config.go
windows-agent/cmd/ubuntu-pro-agent/agent/export_test.go

This adds support for a configuration file to be read and used. Currently, the only options available are verbosity level.
Config files can be located in the current working directory, alongside the binary, in the user's home directory, or in `%UserProfile%/.ubuntupro`. The file must be named `ubuntu-pro-agent.<type>` where `<type>` is one of the file types [supported by Viper](https://github.com/spf13/viper?tab=readme-ov-file#reading-config-files), e.g. `ubuntu-pro-agent.yaml`.
A custom configuration path can be specified by passing the new `--config` flag, which should point to a file that meets the same requirements of Viper described above.
Largely the same as #732.
---
UDENG-2369

feat(windows-agent): Add support for configuration files

---

wsl-pro-service/cmd/wsl-pro-service/service/config.go
wsl-pro-service/cmd/wsl-pro-service/service/export_test.go
wsl-pro-service/cmd/wsl-pro-service/service/service.go
wsl-pro-service/cmd/wsl-pro-service/service/service_test.go
wsl-pro-service/services/wsl-pro.service

This adds support for a configuration file to be read and used. Currently, the only options available are verbosity level.
Config files can be located in the current working directory, alongside the binary, in the user's home directory, or in `/etc/`. The file must be named `wsl-pro-service.<type>` where `<type>` is one of the file types [supported by Viper](https://github.com/spf13/viper?tab=readme-ov-file#reading-config-files), e.g. `wsl-pro-service.yaml`.
A custom configuration path can be specified by passing the new `--config` flag, which should point to a file that meets the same requirements of Viper described above.
This also removes the default `-vv` flags passed to the service.
Largely the same as #721.
---
UDENG-2371

feat(wsl-pro-service): Add support for using configuration file

---

gui/packages/ubuntupro/lib/pages/widgets/status_bar.dart

Very small change that just allows the version text in the status bar of the GUI to be selected for copying.
---
UDENG-2749

feat(gui-ubuntupro): Make version text selectable for copying

---

wsl-pro-service/internal/daemon/daemon_test.go
wsl-pro-service/internal/streams/server_test.go

Some of the wsl-pro-service tests frequently show up as spurious failures, such as `internal/streams/server_tests.go` `TestServe` and `TestStop`. Some observed both in GH CI as well as in Launchpad builds (autopkgtests).
This PR is an attempt to mitigate some non-deterministic failure behavior in this module. Here I focused on the test code itself, as I think I found opportunity for improvement in there. It's possible that some flaky behavior I didn't see or address now will be adressed in futures PRs where I plan to rework the gRPC client creation and reconnection logic, which will have more invasive changes in the production code anyways.
Here's a gist of the reasoning behind the changes:
- `streams.Server.Serve()` - test cases run it in a different goroutine spawn by the test code. The …

fix(wsl-pro-service): Addressing some flakyness

---

docs/tutorial/index.md

This is a **first pass** at improving the main UP4W tutorial.
The main changes here included:
- Edited all main text for clarity and focus
- Added more substantive and focused intro text
- Removed unnecessary and distracting syntax highlighting from CLI code blocks
- Truncated excessively long command logs
- Added shorter, more readable headings, resulting in a more concise contents sidebar
- Made the doc more consistent with the Canonical style guide (e.g., sentence case in headings, no comments in CLI codeblocks, no markup in headings)
The changes resulted in:
- 31% decrease in lines of text
- 15% decrease in page numbers (when rendered as PDF)
- 25% decrease in mouse scrolls from start to finish (estimated from manual testing)
UDENG-2814

docs: UP4W tutorial cleanup

---

docs/index.md
docs/tutorial/index.md

This adds an "In this documentation" section to the landing page that aligns with the Diataxis framework and other product documentation.
A similar content block was removed from the main tutorial and replaced with text that includes internal links to the docs.
This content block was non-functional (there were no working links) and it would have duplicated what is now on the landing page.
UDENG-3001

docs: Format landing page contents

---

windows-agent/internal/daemon/daemon_test.go
windows-agent/internal/proservices/landscape/connection.go
windows-agent/internal/proservices/landscape/service.go
windows-agent/internal/proservices/proservices_test.go
windows-agent/internal/proservices/wslinstance/wslinstance_test.go
wsl-pro-service/internal/daemon/daemon.go
wsl-pro-service/internal/streams/multiclient_test.go
wsl-pro-service/internal/streams/server_test.go

Finally I got time to put some love into this task to carefully analyze the best way to replace `Dial` and `DialContext` in this project. I was especially concerned about the way we depended on the context passed to `DialContext` in tests, but it turned out to be not that hard to do most of the necessary replacements.
The gRPC folks also call out for the builtin retry policies. That's a topic for a follow-up PR, because that's more risky and involving that just the replacement of the deprecated APIs., wihch is just enough to unblock dependabot PR's gRPC and protobuf related PRs.
---
UDENG-2653.

fix: Replace all calls of the grpc-go deprecated Dial* functions

---

wsl-pro-service/debian/rules

Source package build can fail due to go mod vendor needed ssh key access.
Ensure we detect this case and fails early.

maint: ensure vendorizing has been done when building source package

---

wsl-pro-service/internal/system/system.go

All commands should be set to english until we have a proper API for each of them.

fix: force all subprocessed commands in english

---

wsl-pro-service/internal/system/system_test.go

This was lost in the previous PR rebase, sorry for it.

maint: rename TestNew() subtest for system tests

---

wsl-pro-service/services/wsl-pro.service

`pro detach` fails due to livepatch disable failing in a container.
Lifting some systemd service restrictions is enough as a workaround to make it work until a proper fix lands in ubuntu-pro.
Thanks to @CarlosNihelton for the fix.
UDENG-3357

fix: workaround livepatch disable failure

---

docs/custom_conf.py
docs/diagrams/readme.md

This adds the `readme.md` file in the diagrams directory of the docs to the excluded list,
which should prevent build errors associated with the attempt to render the file on RtD.
A small change is also made to the readme to update it based on recent changes to the diagram autogeneration workflow.
UDENG-3361

docs: Exclude diagrams readme

---

wsl-pro-service/internal/daemon/daemon.go

Unset NOTIFY_SOCKET just after forwarding readyness to systemd. This way, subprocesses will not attempt to notify systemd that they are ready.
Unfortunately, this could only be tested in some e2e tests, grepping for subprocess warnings and we are not at that level of details yet in the e2e test infra.
UDENG-3363

fix: prevent subprocesses to sent notification to systemd

---

windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/landscape/service.go
windows-agent/internal/proservices/landscape/utils.go

For provisioning the cloudinit package already does this filtering, and even if there was no need for doing so that code wouldn't change because it needs to translate the `[client]` section to YAML.
We cannot just change `config.LandscapeClientConfig()` to filter stuff out because there are clients relying on it to access the host section. That would imply creating another method to get the full config, which seems as fine as this.

fix(windows-agent): `NotifyConfigUpdate` only distributes the `[client]` section

---

windows-agent/internal/cloudinit/cloudinit.go
windows-agent/internal/cloudinit/cloudinit_test.go
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error-cases
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_obtaining_landscape_config
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_obtaining_pro_token
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_when_the_temp_file_cannot_be_written
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_with_erroneous_landscape_config
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/success
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/with_empty_contents
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/without_hostagent_uid
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/without_landscape
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/without_landscape_[client]_section
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/without_pro_token
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_both_contain_default_tags/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_both_contain_supplied_tags/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_don't_contain_[host]_section/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_only_contains_[client]_section)/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_with_default_tags/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_with_supplied_tags/agent.yaml
windows-agent/internal/proservices/testdata/TestNew/golden/when_the_config_cannot_check_if_it_is_read-only
windows-agent/internal/proservices/testdata/TestNew/golden/when_the_subscription_stays_empty

We should use `ubuntu_pro` module instead. `cloud-init` does understand `ubuntu_advantage`. Their docs state:
> Activate only on keys: ubuntu_pro, ubuntu-advantage, ubuntu_advantage
Yet, there are about 4 months since they deprecated ubuntu_advantage: https://github.com/canonical/cloud-init/pull/4865
Docs are up-to-date, so current users are likely to add `ubuntu_pro` key in their user-data. That wouldn't clash with the agent.yaml, in fact which token would then be applied can become unpredictable as both would reach cc_ubuntu_pro.py module.
So, inline with cloud-init docs, let's migrate to the `ubuntu_pro` key :)
I suspect @didrocks and @jibel faced this exact behavior (mix of both keys) during their tests.
Ah, I also sneaked a fix in the `#cloud-config` stenza. It's not been a problem …

fix(windows-agent): Deprecate `ubuntu_advantage` 

---

gui/packages/ubuntupro/lib/l10n/app_en.arb

That name is ubiquitous in Landscape docs
But look a bit cryptic to most users.
Here's how it looks after this small change:
---
Fixes UDENG-3259 and #801

fix: Replaces Landscape "FQDN" with "server address"

---

CONTRIBUTING.md

Link to script for building the Windows Agent was to `build-deb.ps1` but it should be `build-deb.sh`.
Note: this is linked correctly in the most recent `CONTRIBUTING.md` for the Ubuntu WSL docs.
UDENG-3594

docs: Fix broken link to build script in contributing.md

---

windows-agent/internal/proservices/landscape/executor.go
windows-agent/internal/proservices/landscape/executor_test.go

We didn't notice this behaviour in tests because our mocked file server was serving files in the root directory (since the parent of / is / everything just worked).
Changing tests to serve and search files inside a subdirectory reveal the problem: we're not looking for the checksums file beside the rootfs but rather in the parent directory. We see log lines like below:
> time="2024-07-18T10:42:53-03:00" level=debug msg="Landscape: received command Install. Target: testDistro_UP4W_TestInstall_Error_when_the_checksum_entry_is_missing_for_the_rootfs_5721719220902747386"
> time="2024-07-18T10:42:53-03:00" level=info msg="checksums file http://127.0.0.1:57850/releases/SHA256SUM" not found"
---
UDENG-3669

fix(agent): SHA256SUMS being looked up in the parent directory

---

docs/reference/landscape.md
docs/tutorial/index.md

This PR makes references to the Landscape configuration file in the docs more consistent with the Ubuntu Pro For WSL UI, which includes a placeholder for `landscape.conf` during setup.
In `reference/landscape.md` it is now mentioned that this is a plain text file and that other extensions, such as `.ini` can also be used.
UDENG-3592

docs: Make refs to config file extension more consistent with UI

---

gui/packages/ubuntupro/integration_test/ubuntu_pro_for_wsl_test.dart
gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/landscape/landscape_model.dart
gui/packages/ubuntupro/lib/pages/landscape/landscape_page.dart
gui/packages/ubuntupro/lib/pages/widgets/page_widgets.dart
gui/packages/ubuntupro/test/pages/landscape/landscape_data_model_test.dart
gui/packages/ubuntupro/test/pages/landscape/landscape_model_test.dart
gui/packages/ubuntupro/test/pages/landscape/landscape_page_test.dart
gui/packages/ubuntupro/test/testdata/landscape/custom.conf

Adding one single field motivated a whole UI redesign. The discussion and thought process is documented in #802 .
The key pilar to understand this PR is: we no longer show relationship between the form fields being displayed, but rather separate them into subforms so the fields that are visible are the ones relevant to the type of configuration the user is currently doing.
[This comment in #802](https://github.com/canonical/ubuntu-pro-for-wsl/issues/802#issuecomment-2237200764) summarizes what I mean by inter-field relationship, non-trivial logic that would disable or enable or change the forbidden values of a form field depending on the values of neighbour fields. The previous logic was at the limit of being fine because the form was small, adding just one extra field was enough to turn …

feat(gui): Landscape redesign to fit an input field for the SSL key

---

gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/landscape/landscape_page.dart

Thanks @edibotopic for noticing that :)
Additional to that fix. the first commit of this PR moves a user-facing string (SSL Key input label) from the source code to the translatable resource, so it can be properly localized.

fix(gui): SSL public key hint must have a certificate file extension

---

gui/packages/ubuntupro/lib/pages/landscape/landscape_model.dart
gui/packages/ubuntupro/pubspec.lock
gui/packages/ubuntupro/pubspec.yaml
gui/packages/ubuntupro/test/pages/landscape/landscape_data_model_test.dart

The Landscape ping service doesn't support https by default.
Additionally, wslpath can fool wsl-pro-service, when the path passed to the command line is an empty path it outputs the current working directory absolute path. Due systemd, cwd is `/`.
We should have wsl-pro-service checking for empty paths before invoking wslpath for added correctness (users could well assemble a config file by hand having `ssl_public_key = `), but it also makes sense to fix it here, as we're aware of which fields are optional in the UI. But, instead of treating this (or any path) field as special, I'm being more generic, **filtering out any line in the INI configuration output that could have empty values**, i.e., we won't output lines with this shape : `key =`.
More test assertions were added validating …

fix(gui): Landscape config serialization

---

wsl-pro-service/internal/system/landscape.go
wsl-pro-service/internal/system/system.go
wsl-pro-service/internal/system/system_test.go
wsl-pro-service/internal/system/testdata/TestEnsureValidLandscapeConfig/golden/do_not_transform_windows_ssl_certificate_empty_path
wsl-pro-service/internal/system/testdata/landscape.conf.d/windows_ssl_empty.conf
wsl-pro-service/internal/testutils/mock_executables.go

I wanted this PR to be laser-focus, just a bugfix, thus I'm not refactoring the executable-mocking just yet.
The issue is: when we invoke `wslpath -au ''`  we get the absolute path of the current working directory.
That's surely not what we expect of a Windows path.
It could be problematic if the user passes a custom Landscape config file containing this line `ssl_public_key= `, as we'd modify the final client.conf into `ssl_public_key = /` (systemd makes it so our current working directory is `/`). Landscape client would tolerate the empty value in the INI sintax, but this would force it to try to read `/` as a certificate file. Clearly not what we want.
A similar thing could happen in `system.UserProfileDir()`, but that's even funnier. Having %USERPROFILE% set to an empty string is …

fix(wsl-pro-service): Do not translate empty paths

---

docs/.sphinx/get_vale_conf.py

This updates the configuration settings for the [Vale](https://vale.sh/) linter, based on recent changes to the docs Starter Pack.
The linter now works as expected. Running checks on a specific file can be done as follows:
`make vale TARGET=tutorial/getting-started.md`
This prints a list of errors, suggestions and warnings relating to documentation style, such as:
` 162:1   warning     Avoid inline comments in codeblocks   Canonical.016-No-inline-comments`
UDENG-3785

docs: Update vale config to get vocab dependency

---

gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/landscape/landscape_page.dart

This hides the Landscape config option (instead of disabling it). No changes in behaviour nor in how we decide to hide it.
Some strings were changed also per guidance provided in #861. 
Finally I added a little bit more spacing in the top now that the subtitle is one line only.
Here's how it looks like when compiled in release mode.
Closes #861 
---
I'm purposefully basing this PR on top of #873 so I can stress CI to exercise the changes therein introduced. There is no dependency between the two tasks.
---
UDENG-3818

fix(gui): Slicker Landscape config page

---

gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_widgets.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_widgets_test.dart

Sometimes copy-pasting a pro token comes with trailing spaces. Neither leading, trailing or even middle spaces are alloweable in a token. This PR leverages Flutter builtin mechanisms to filter input supplied to the token text field such that any kind of whitespaces (not only the ASCII ones) are discarded before any further processing.
Closes #857 
---
I'm purposefully basing this PR on top of #873 so I can stress CI to exercise the changes therein introduced. There is no dependency between the two tasks.
---
UDENG-3810

fix(gui): Remove spaces from the Pro token input field

---

windows-agent/internal/cloudinit/cloudinit.go
windows-agent/internal/cloudinit/cloudinit_test.go
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/with_empty_contents
windows-agent/internal/proservices/proservices_test.go
windows-agent/internal/proservices/testdata/TestNew/golden/when_the_config_cannot_check_if_it_is_read-only
windows-agent/internal/proservices/testdata/TestNew/golden/when_the_subscription_stays_empty

When the config is empty, the yaml serialization outputs {}. We still added some commentary in the agent.yaml, resulting in a bunch of nothing that confused cloud-init, because it's enablement is based on the existence of the files, their contents are only checked later. That wouldn't be a problem per se, as the WSL datasource would recognize there's nothing to do and bail out, but that would have costed unnecesary CPU cicles, and worse than that, the current implementation of cloud-init makes it log as an error the fact that there is nothing to do at this point, which results in more noise if the user see the output of cloud-init status --long.
The fix is rather simple: do not write an empty object into agent.yaml. If the config is empty we delete that file. This way, if there is nothing …

fix(agent): No empty cloudinit

---

storeapi/go-wrapper/microsoftstore/errors.go
storeapi/go-wrapper/microsoftstore/export_test.go
storeapi/go-wrapper/microsoftstore/store.go
storeapi/go-wrapper/microsoftstore/store_test.go
storeapi/go-wrapper/microsoftstore/store_windows.go
windows-agent/internal/daemon/daemon_test.go
windows-agent/internal/daemon/daemontestutils/networking_mock.go
windows-agent/internal/daemon/networking.go
windows-agent/internal/proservices/landscape/distroinstall/distroinstall.go
wsl-pro-service/internal/system/networking.go

Most of the warnings were not a real issue, but the one around the Win32 GetAdapterAddersses was harder to prove with the previous implementation so I refactored it a little bit to make it easy to reach the piece of mind that we're not doing nasting error-prone narrowing conversions.
This should unblock #877 .
UDENG-4234

fix: golangci-lint warnings about unsafe integer conversions

---

windows-agent/internal/distros/worker/task_queue.go
windows-agent/internal/distros/worker/worker_test.go
windows-agent/internal/proservices/landscape/landscape_test.go
wsl-pro-service/internal/streams/server.go

The tests that fail often are contained in  `windows-agent/internal/distros/worker/worker_test.go`. they all show the same pattern: 
1. worker.SubmitTasks submits an immediate task.
2. the already running goroutine processing tasks is expected to be notified and dequeue that task.
3. require.Eventually asserts the side effects of that task.
I could find half explanation for the failure mode observed: 
```
time="2024-07-26T15:14:24Z" level=debug msg="Distro \"testDistro_UP4W_TestTaskProcessing_Success_executing_a_task_7763261449570405205\": starting task processing"
time="2024-07-26T15:14:24Z" level=info msg="Distro \"testDistro_UP4W_TestTaskProcessing_Success_executing_a_task_7763261449570405205\": Submitting tasks [\"Test task\"] to queue"
time="2024-07-26T15:14:25Z" level=debug …
```

fix: Some flakyness in windows-agent and wsl-pro-service

---

common/grpc/logconnections/logconnections_test.go
end-to-end/main_test.go
storeapi/go-wrapper/microsoftstore/store_test.go
windows-agent/internal/distros/distro/distro_test.go
windows-agent/internal/distros/worker/worker_test.go
windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/proservices_test.go
windows-agent/internal/proservices/wslinstance/wslinstance_test.go
wsl-pro-service/cmd/wsl-pro-service/service/service_test.go
wsl-pro-service/internal/daemon/daemon_test.go

When upgrading golangci-lint in #870 I introduced a bunch of os.Exit calls in test functions blindily following the SA300 warning. That's bad, because it prevents the Go runtime to perform some clean-up after `m.Run()` returns.
In fact, [Go 1.15 changelog](https://go.dev/doc/go1.15#testingpkgtesting) clearly states that m.Run() does the right thing in regards to the program's exit code. `staticcheck` running alone won't report that warning. `golangci-lint` is failing to propagate the go version, thus confusing the downstream linter.

fix(test): No `os.Exit()` calls in `TestMain` and no SA3000 warning

---

gui/packages/ubuntupro/lib/core/agent_connection.dart
windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
windows-agent/internal/daemon/daemon.go
windows-agent/internal/daemon/daemon_test.go
windows-agent/internal/daemon/daemontestutils/daemontestutils.go
windows-agent/internal/daemon/daemontestutils/netmonitoring_mock.go
windows-agent/internal/daemon/export_test.go
windows-agent/internal/daemon/internal_test.go
windows-agent/internal/daemon/netmonitoring/netmonitoring.go
windows-agent/internal/daemon/netmonitoring/netmonitoring_linux.go
windows-agent/internal/daemon/netmonitoring/netmonitoring_windows.go
windows-agent/internal/daemon/netwatcher.go
windows-agent/internal/daemon/netwatcher_test.go
windows-agent/internal/daemon/networking.go
windows-agent/internal/proservices/proservices.go
windows-agent/internal/proservices/proservices_test.go

The key of this PR is enable a sensible behaviour for the Windows agent when there is no WSL network adapter, which is also when there is no WSL instance registered. It's behaviour remain changed otherwise. When started under such condition:
- The proservices skip registering the WSL instance gRPC service
- The daemon subscribes to OS notifications related to additions of network interfaces
- If triggered with the WSL adapter in the list of new interfaces recently added, restarts itself, i.e.
* stops the current gRPC server and 
* creates a new one with all proservices enabled
A live demonstration of this huge patch on a fresh VM with the latest stable WSL and Ubuntu-24.04 from the package flight:
https://github.com/user-attachments/assets/e35f36b8-318b-4d98-b6ab-0b59f4b1fff1
The daemon …

fix(windows-agent): Don't bail out if WSL adapter is not available

---

windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
windows-agent/cmd/ubuntu-pro-agent/agent/config.go

`%USERPROFILE%\.ubuntupro`.
The fix I'm proposing here is the simplest but maybe less correct if we consider that the public dir could point to anywhere else other than the default (`%USERPROFILE%\.ubuntupro` when in production). 
The issue is: when configuring viper we added `$HOME/.ubuntupro` to the config paths. Since `$HOME` is not defined on Windows nor `/` is the default path separator, that addition never worked. By ensuring we use the correct path separator, we allow viper to consider `%HOMEDRIVE%` , `%HOMEPATH%` and `%USERPROFILE%`  for `$HOME` (viper's implementation details).
The test case `"When the config is in user's public directory"` would only fail on Windows.

fix(windows-agent): Can't find config file inside the public dir

---

docs/.custom_wordlist.txt
docs/custom_conf.py
docs/howto/custom-rootfs-multiple-targets.md
docs/howto/index.md
docs/howto/set-up-up4w.md
docs/reference/firewall_requirements.md
docs/tutorial/getting-started.md

This PR makes heavy use of tabbed code blocks to show alternative ways to do things with Bash and PowerShell.
Both alternatives were tested. The bash one comes from the [Landscape documentation](https://ubuntu.com/landscape/docs/use-a-specific-ubuntu-image-source-for-wsl#installing-with-a-custom-image), I essentially extracted the piece I was more concerned about (custom rootfs with cloud-init data) and made a self-contained guide out of it (plus translating to PowerShell).
---
UDENG-4694

docs: How-to create WSL instances on multiple Windows machines via Landscape API

---

windows-agent/internal/distros/distro/touchdistro/touch_distro_gowslmock.go
windows-agent/internal/distros/distro/touchdistro/touch_distro_linux.go
windows-agent/internal/distros/distro/touchdistro/touch_distro_windows.go
windows-agent/internal/proservices/landscape/executor.go
windows-agent/internal/proservices/landscape/executor_test.go

This PR augments the touchdistro package to provide a function that waits on cloud-init. Whether it errors or not only affect logging, thus we can provide simpler mocks. The important part is: we need to run the new function when installing a distro from a custom rootfs, when there is no distro launcher to do so.
----
UDENG-4066

fix(windows-agent): Run cloud-init when installing from a tarball

---

.github/actions/build-msix/action.yml
.github/workflows/qa-azure.yaml

Making it in its own action will let us reuse that part when creating the publishing CI workflow.

ci: Factor out building the MSIX

---

.github/actions/build-msix/action.yml
.github/workflows/publish-msix.yaml
msix/SBConfig.json
tools/build/compute_version.go

This reuses the MSIX build action and relies on the StoreBroker PowerShell module to push the updates to the Partner Center.
I'm tagging this commit as a "fake release" so we can see the workflow in action bumping the package version.
We only track package versioning in Git, the MSIX version is declared in the appx manifest as 0.0.0.0 and should remain like that as we compute the version dynamically from the closest Git tag and edit the appx manifest on the fly as part of the CI job. Similarly the binaries have a full version string computed in the same way, just more descriptive as they also contain a build number and the commit short SHA-1 (remember the last (fourth) section of the version number [is reserved for Store use and must be left as …

ci: Creates a workflow to publish the MSIX automatically

---

gui/packages/ubuntupro/lib/pages/landscape/landscape_page.dart
gui/packages/ubuntupro/test/pages/landscape/landscape_page_test.dart

The file picker for Landscape configuration certificates now filters to only .cer, .crt, .der, and .pem file types.
Fixes https://github.com/canonical/ubuntu-pro-for-wsl/issues/878
---
UDENG-5110

fix(gui-ubuntupro): Add filters for cert files in file picker

---

msix/UbuntuProForWSL/Package.appxmanifest
windows-agent/cmd/ubuntu-pro-agent/agent/agent.go
windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
windows-agent/cmd/ubuntu-pro-agent/agent/export_test.go
windows-agent/cmd/ubuntu-pro-agent/agent/lockfile_linux.go
windows-agent/cmd/ubuntu-pro-agent/agent/lockfile_windows.go

We modify the MSIX packaging to create an [app execution alias](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap3-appexecutionalias), which causes a dummy binary to be created in a well-known location (by default `%LOCALAPPDATA%\Microsoft\WindowsApps`) which is included in user's `%PATH%` such that it becomes possible for the user (or scripts running in user's behalf) to run the agent via CLI. That's preferrable over declaring the agent as an [Application](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application) because it won't be "promoted" in the start menu as an application would. Users can still find the CLI executable by searching for its exact name ( `ubuntu-pro-agent` in this case - the `.exe` is …

feat(windows-agent): Allow users to run it via CLI

---

.gitignore
gui/packages/ubuntupro/.gitignore

At the top level, .vscode/ gets generated any time a custom vscode setting is set for the workspace, leading to changes that don't necessarily need committed (for example, my spell checker that I add spelling exceptions to).
In gui/ubuntupro/, devtools_options.yaml gets generated any time you open VS Code's devtools. Since we don't use any custom options here, I think this can be ignored.

maint: Add additional files to ignore

---

gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_page.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_page_test.dart

Removes the popup as well as the test that asserts its existence. The tests for the pro token field that already exist should be enough to test error functionality.
---
UDENG-5286

fix(gui-ubuntupro): Remove popup feedback when applying a token

---

gui/packages/ubuntupro/lib/core/pro_token.dart
gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_widgets.dart
gui/packages/ubuntupro/test/core/pro_token_test.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_model_test.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_page_test.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_widgets_test.dart
gui/packages/ubuntupro/test/pages/subcribe_now/token_samples.dart
gui/packages/ubuntupro/test/utils/token_samples.dart

Removes specific errors like "too short" or "too long". Also, removes any error message when the token field is cleared. This change also streamlines some of the tests so we test multiple cases of different kinds of invalid tokens, but now each results in the same error.
---
UDENG-5285

fix: Streamline token errors

---

gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_page_test.dart

This happened because #967 removed a test that was no longer needed (as well as this import), but was not removed in main before the branch for #968 was created. Since the import had to change for the relocation of common tokens, git didn't merge the changes quite correctly.

fix: Remove accidental inclusion of an unused import

---

gui/packages/ubuntupro/end_to_end/end_to_end_test.dart
gui/packages/ubuntupro/integration_test/ubuntu_pro_for_wsl_test.dart
gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_page.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_page_test.dart

Changes the text of the "Subscribe Now" button to "Get Ubuntu Pro". Also, hides the button by default unless purchasing is allowed (instead of being greyed out).
---
UDENG-5283

fix: Adjust "Subscribe Now" button copy and hide by default

---

gui/packages/ubuntupro/lib/app.dart

This change reverts back to using the Yaru themes as-is instead of injecting our own styles for buttons. This matches the rounded nature of Yaru buttons, as well as the more bold text in them.
<details>
<summary>Screenshots</summary>
</details>
---
UDENG-5281

fix: Rounds all buttons and removes custom button styles

---

gui/packages/ubuntupro/end_to_end/end_to_end_test.dart
gui/packages/ubuntupro/integration_test/ubuntu_pro_for_wsl_test.dart
gui/packages/ubuntupro/lib/constants.dart
gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_widgets.dart
gui/packages/ubuntupro/lib/pages/subscription_status/subscription_status_widgets.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_widgets_test.dart

Shows the token input field always instead of being in a collapsible section. Also, adds messaging when a valid token or invalid token is added, with an icon.
A small detail I missed when adjusting the copy for errors previously: invalid tokens now show the string "Invalid token" instead of "Token invalid".
<details>
<summary>Screenshot of the default look</summary>
</details>
<details>
<summary>Screenshot when an invalid token is entered</summary>
</details>
<details>
<summary>Screenshot when a valid token is entered</summary>
</details>
Our designs in Figma include functionality that we do not have, so I took some creative liberties in adapting it to the current layout. Let me know if it needs any adjustments.
---
UDENG-5284

feat: Always show Pro token input

---

gui/packages/ubuntupro/lib/l10n/app_en.arb
gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_model.dart
gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_page.dart
gui/packages/ubuntupro/pubspec.lock
gui/packages/ubuntupro/pubspec.yaml
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_page_test.dart
gui/packages/ubuntupro/test/pages/subcribe_now/subscribe_now_page_test.mocks.dart

Moves the About Ubuntu Pro button functionality to a Learn More link in the above copy. Also fixes the issue of the link not opening.
---
UDENG-5282

fix: Move about link and fix broken link

---

gui/packages/ubuntupro/lib/pages/widgets/page_widgets.dart

Centers the title bar control buttons, but they will not be the full height of the title bar until Yaru is updated to include https://github.com/ubuntu/yaru.dart/pull/967 (will require a version bump on our end in the future).
| Existing | Current state of this PR | With the Yaru update |
|----------|--------------------------|----------------------|
| ![image](https://github.com/user-attachments/assets/0aa75361-b065-4abf-b734-64c5936a6a00) | ![image](https://github.com/user-attachments/assets/eebb0dee-656a-4443-93d2-c954a45bb8c7) | ![image](https://github.com/user-attachments/assets/63aa2cbf-d027-4caf-bed7-1be1d07621e2) |
---
UDENG-5289

fix: Vertically center window title bar controls

---

windows-agent/cmd/ubuntu-pro-agent/agent/agent.go
windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
windows-agent/internal/daemon/daemon.go
windows-agent/internal/daemon/daemon_test.go

Since #896 the agent might sometimes close the `a.ready` channel too early, giving the possibility of a call to `a.WaitReady()` exiting before the daemon really starts serving, thus not really waiting.
The deamon knows best when is the most likely moment to be serving, thus this PR slightly modifies `a.WaitReady()` to check with the daemon, which had to implement its own `daemon.WaitReady()`.
The `a.ready` channel is still useful to synchronize the access to `a.daemon`, preventing nil pointer access when the deamon is not yet initialized. Checking for `nil` is still needed, as the `a.ready` channel may be closed without ever serving, such as on a failure case.
This adds a test for `daemon.WaitReady()`, but the agent tests don't need to change, as their "flakyness" reveal the problem.
--- …

fix(windows-agent): Delegates `agent.WaitReady` to the daemon

---

windows-agent/internal/daemon/daemontestutils/networking_mock.go

If the system receives an IPv6 address, then running the agent with mocks (for example, when running integration tests) can result in panics. This fixes that issue by checking if the IP is convertible to Ipv4.
For context, this came up when I attempted to run the Flutter integration tests on a network and host that technically support IPv6.

fix(windows-agent): Check that IPs are convertible to ipv4

---

common/go.mod
common/go.sum
end-to-end/go.mod
end-to-end/go.sum
tools/go.mod
tools/go.sum
windows-agent/go.mod
windows-agent/go.sum
windows-agent/internal/proservices/landscape/utils.go

```
time=2024-07-24T12:17:10-07:00 level=error msg=Landscape:  skipping distro "Ubuntu-24.04" from landscape info: could not get distro "Ubuntu-24.04"'s state: could not get states of distros: exit status 1. Stdout: . Stderr:
```
That happens during construction of the status message sent to Landscape. If we skip a distro, Landscape understands it doesn't exist anymore and removes it from the dashboard. But that happens sometimes when an existing distro. It seems a WSL internal error.
https://github.com/ubuntu/GoWSL/pull/120 should prevent the stdout and stderr messages to come empty as shown above.
Thus I'm updating GoWSL here.
That doesn't prevent the issue itself.
I couldn’t reproduce this outside of UP4W. I attempted building a small binary in Go doing the same steps as GoWSL does and …

maint(windows-agent): Investigate skipping distros

---

gui/packages/ubuntupro/lib/pages/subscription_status/subscription_status_widgets.dart

This effectively aligns the colors correctly with what is used by Yaru for info boxes, which you can see at https://ubuntu.github.io/yaru.dart under the "YaruInfo" tab. Our colors in light mode were identical to Yaru, but dark mode colors were not. This fixes that issue and simplifies the widget code significantly by just using the `YaruInfoBox`.
This page still needs more changes in the future, but this should be sufficient for notification colors for the time being.
| | Dark | Light |
|-|------|-------|
| Existing | ![image](https://github.com/user-attachments/assets/31c464f3-90f5-4914-80ef-8f7734c65d0d)| ![image](https://github.com/user-attachments/assets/cca4c2a4-5374-4795-804f-ba5ccf116e31) |
| New | ![image](https://github.com/user-attachments/assets/2cf363ef-d4c8-4a8b-a053-7a68d4260 …

fix: Use YaruInfoBox for notification boxes

---

gui/packages/ubuntupro/lib/pages/landscape_skip/landscape_skip_page.dart
gui/packages/ubuntupro/lib/pages/widgets/radio_tile.dart

Adds a border to the radio tiles, as well as a background to unselected tiles.
| | Dark | Light |
|-|------|-------|
| Existing | ![image](https://github.com/user-attachments/assets/2ef62668-b341-48b0-b263-4bfdd0283393) | ![image](https://github.com/user-attachments/assets/1c91dcf4-d825-47f7-8708-1c15a75d4273) |
| New | ![image](https://github.com/user-attachments/assets/584b61e2-19c1-4657-aa3c-349ed98008b9) | ![image](https://github.com/user-attachments/assets/72094385-06c9-46ca-b00e-bf1a8c223fa9) |
This is also based on https://github.com/canonical/ubuntu-pro-for-wsl/pull/997 and relies on it being merged first.
---
UDENG-5593

fix: Fix radio background

---

docs/howto/set-up-landscape-client.md
docs/reference/landscape_config.md

Until version 0.1.15 (the current version tag) of Ubuntu Pro for WSL, the app explicitly requires referencing a path to the SSL certificate on a Windows host machine.
The fix was implemented in #995. Now the agent completely follows the Windows OS certificate stores, only requiring reference to that certificate if the machine running the Landscape server is not trusted on a particular network. But we didn't issue a new release since then. So, to avoid a new release so close to the end-of-year holidays, let's update the docs in an atomic way, so we can easily revert if we deem worth it after the new year and a new release comes out.
The changes herein introduced look like the following:
and
---
UDENG-5654

fix(docs): Explicits the agent's requirement on the server SSL public key

---

gui/packages/ubuntupro/pubspec.lock
gui/packages/ubuntupro/pubspec.yaml

Bumps Yaru to 6.0.0 (and yaru_test to 0.3.0), which includes [my fix for the title bar](https://github.com/ubuntu/yaru.dart/pull/967), as pictured here:
(Also note the new dark mode colors from Yaru 6)
---
UDENG-5691

deps: Bump Yaru to 6.0.0

---

gui/packages/ubuntupro/lib/main.dart
gui/packages/ubuntupro/pubspec.lock
gui/packages/ubuntupro/pubspec.yaml

Sets a minimum window size to the current default size. The window may be resized to be larger but cannot be resized to be smaller. This also centers the window on the screen when it opens instead of being in the top left corner.
This works, but it might be worth considering an update to https://github.com/ubuntu/yaru_window.dart to include a `setMinimumSize` and `setMaximumSize` method to `YaruWindow` instead of having to use `window_manager` directly.
---
UDENG-5682

fix: Set a minimum size for the window

---

gui/packages/ubuntupro/lib/constants.dart
gui/packages/ubuntupro/lib/main.dart
gui/packages/ubuntupro/lib/pages/widgets/page_widgets.dart

Sets a maximum width for page content, equal to their current effective width.
Here's a comparison for this change (maximized on a 1440p screen):
| Old | New |
|-----|-----|
| ![image](https://github.com/user-attachments/assets/623d1d22-84d7-4c66-8580-f0b0cfd38f66) | ![image](https://github.com/user-attachments/assets/5a78057f-c684-4a57-a988-cd70268aad1b) |
The default size of the app remains unchanged.
*This diff is really just the content being wrapped with a new widget, nothing else changed*
---
UDENG-5684

fix: Set a maximum size of page contents

---

gui/packages/ubuntupro/lib/pages/landscape/landscape_page.dart
gui/packages/ubuntupro/lib/pages/widgets/delayed_text_field.dart

Hides errors for inactive fields since they are not relevant; when reactivated the errors will reappear.
Also fixes a small bug that caused fields not to be properly disabled on the Landscape page.
---
UDENG-5732

fix(gui-ubuntupro): Hide inactive errors

---

gui/packages/ubuntupro/lib/constants.dart
gui/packages/ubuntupro/lib/pages/subscribe_now/subscribe_now_widgets.dart
gui/packages/ubuntupro/lib/pages/widgets/delayed_text_field.dart
gui/packages/ubuntupro/test/utils/build_multiprovider_app.dart
gui/packages/ubuntupro/windows/runner/main.cpp

When entering text into a text field that may display an error, the text field and other content on the page will move to accomodate the error text. This change adds a SizedBox when there is no error to prevent this movement. As a result, page content is naturally longer, so the default window height has been increased by 50 pixels.
*Depends on https://github.com/canonical/ubuntu-pro-for-wsl/pull/1043*
---
UDENG-5680

fix(gui-ubuntupro): Add placeholder padding to text fields to prevent jittering

---

wsl-pro-service/internal/system/landscape.go
wsl-pro-service/internal/system/system_test.go
wsl-pro-service/internal/system/testdata/TestEnsureValidLandscapeConfig/golden/do_not_rerun_landscape_due_whitespace_changes
wsl-pro-service/internal/system/testdata/landscape.conf.d/no_change_due_spaces.conf
wsl-pro-service/internal/testutils/mock_executables.go

This is a two-fold fix.
I noticed that wsl-pro-service was causing the machine to re-register with Landscape at every startup. There is an early routine that checks for the validity of the Landscape client config file contents, amending it if necessary and re-running landscape-config **if anything changed**. The current implementation also considers whitespace changes as a valid reason to re-run landscape-config, which shouldn't be the case.
An instrumented build to diff the contents before and after that routine revealed that we're taking whitespace changes too seriously.
```
n@mib01:~$ sudo /mnt/d/wsl-pro-service -vvv
INFO Starting WSL Pro Service version Dev
INFO /home/cn/Dev/1_Work/up4w/wsl-pro-service/cmd/wsl-pro-service/service/config.go:48 initViperConfig() No configuration file: …
```

fix(wsl-pro-service): Prevents unnecessary re-registration with Landscape 

---

gui/packages/ubuntupro/lib/pages/landscape_skip/landscape_skip_page.dart
gui/packages/ubuntupro/lib/pages/widgets/navigation_row.dart

Adds an option to use elevated or outlined buttons for "next" navigation. Non-action buttons should be outlined instead of elevated.
*Note "Next" is outlined instead of green*

fix: Add option to use non-elevated buttons for navigation

---

.github/workflows/cla-check.yaml

Skips running the CLA check if the PR is opened by Weblate, since we can't guarantee verification.
Same as https://github.com/ubuntu/app-center/blob/main/.github/workflows/pr.yaml#L7C5-L7C89
Example of a failing Weblate PR for reference: https://github.com/canonical/ubuntu-pro-for-wsl/pull/1079
---
UDENG-266

ci: Ignore CLA for Weblate PRs

---

windows-agent/internal/cloudinit/cloudinit.go
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_obtaining_landscape_config
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_obtaining_pro_token
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_when_the_temp_file_cannot_be_written
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/error_with_erroneous_landscape_config
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/success
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/without_hostagent_uid
windows-agent/internal/cloudinit/testdata/TestUpdate/golden/without_pro_token
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_don't_contain_[host]_section/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_only_contains_[client]_section)/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_with_default_tags/agent.yaml
windows-agent/internal/proservices/landscape/testdata/TestNotifyConfigUpdateWithAgentYaml/task_and_agent.yaml_with_supplied_tags/agent.yaml
windows-agent/internal/proservices/testdata/TestNew/golden/when_the_config_cannot_check_if_it_is_read-only
windows-agent/internal/proservices/testdata/TestNew/golden/when_the_subscription_stays_empty

And prevent schema warnings.
Following the prescription of the spec WS040, I'm adding the three fields to the serialized Landscape client config into `agent.yaml` so that when cloud-init invokes `landscape-config`, instead of attempting a new registration right away, it will just write the client configuration file, possibly incomplete at this point in time.
`wsl-pro-service` is already prepared to complete that configuration file and issue the registration request.
---
UDENG-5888

feat(windows-agent): cloudinit module to defer Landscape registration

---

windows-agent/internal/proservices/landscape/executor.go
windows-agent/internal/proservices/landscape/executor_test.go

WS040 explains the other alternatives. We chose the simplest. We assume that cloud-init won't register the instance with Landscape. Instead, wsl-pro-service will do it at some point after cloud-init finishes. Thus just waiting on cloud-init is not enough.
Adding this wait revealed a bug in how we test receiving commands from a mocked Landscape server. The fix is much shorter than the explanation.
[Here CI shows the bug](https://github.com/canonical/ubuntu-pro-for-wsl/actions/runs/13053345773/job/36418338768#step:7:1025). We panic because the Landscape component inside the agent is still running and trying to assemble a host info message to send to the server, but the context used by the internal distros database was already cancelled, so the database caused the panic. That happens because …

fix(windows-agent): Wait 5s after installing a distro per Landscape request

---

.github/workflows/qa-azure.yaml

End to End tests can't run when translations are submitted via Weblate, so just skip running those workflows when the only files that change are translations
---
UDENG-266

ci: Do not run end to end tests for translation changes

---

docs/reference/distributions.md

These changes include clarifications and fixups for the reference page on Ubuntu WSL distributions.
Main changes:
* Improved phrasing and made it more consistent. Example: we should not use "flavour" because it has another, common denotation in the context of Ubuntu.
* Clarified release section. Added a title to distinguish it from the rest of the text. More detail is now provided on upgrading and support for interim releases.
* Edits to Naming section. Fixed some difficult-to-read phrases. Added some examples for the different contexts to make them more tangible.
* Note on kernel support. Added a note that we do not maintain the kernel, with a link to the WSL kernel repo.
Special thanks to @davidekete for his excellent contributions to the reference through [this …

docs: Update distro ref

---

gui/packages/ubuntupro/lib/pages/widgets/delayed_text_field.dart
gui/packages/ubuntupro/lib/pages/widgets/page_widgets.dart

Some strings for other languages could overflow the GUI, so this accounts for vertical increases in the layout of each page by wrapping the content in a scrollable container. The CenteredPage widget used for the status page should never realistically overflow, but its scrollable just in case :) (and it will be expanded in the future).
Also allows more than 1 line for error/hint messages, and truncates long label texts.
<details>
<summary>Label truncation and multiline error example (PL translations)</summary>
</details>
---
UDENG-5996

fix: Handle potentially long translation strings

---

docs/custom_conf.py

It's common for docs that are open to user contributions to have an edit icon at the top of the page.
This is more immediate than the edit-this-page text, which is currently buried at the bottom of each page.
The change is a simple way to encourage small contributions.
UDENG-6061

docs: add edit button to docs pages

---

docs/explanation/index.md
docs/howto/index-contributing.md
docs/howto/index-gpu-and-graphics.md
docs/howto/index-remote-deployment.md
docs/howto/index-setup.md
docs/howto/index.md
docs/index.md
docs/pro_content_notice.txt
docs/reference/index.md
docs/tutorials/index.md

Includes changes to landing pages:
* improves structure of first-level landing pages (e.g., `how-to guides`), primarily with titles
* adds structure to second-level landing pages (e.g., `how-to guides > remote deployment`), primarily with titles
* not possible to remove top-level bullet point that links to landing pages themselves, but the linked page is made more useful with the additional structure
* in the process, tries to better surface specific content, like Landscape versus Intune for deployment.
Also includes changes to the homepage:
* Removes the UP4W/Pro notice: not good to have as first piece of information in the docs. That the app is in-development is mentioned in the text and in the (updated) Pro notice included on UP4W-specific pages
* Adds direct links to pages: links to …

docs: additional landing page structure

---

common/go.mod
common/go.sum
end-to-end/go.mod
end-to-end/go.sum
tools/go.mod
tools/go.sum
windows-agent/cmd/ubuntu-pro-agent/agent/export_test.go
windows-agent/go.mod
windows-agent/go.sum
windows-agent/internal/distros/distro/touchdistro/touch_distro_windows.go
windows-agent/internal/proservices/landscape/distroinstall/distroinstall.go
windows-agent/internal/proservices/landscape/distroinstall/distroinstall_gowslmock.go
windows-agent/internal/proservices/landscape/distroinstall/distroinstall_test.go
windows-agent/internal/proservices/landscape/executor.go
windows-agent/internal/proservices/landscape/executor_test.go

I think this is better reviewed commit by commit, as there are some "peasant fixes" along the way which do not exactly strictly meet the core of this PR, but they were small enough to not deserve a new PR (I think :) ).
This "feature" addresses one specific problem made more evident now that the latest stable version of WSL handles "modern distros" (those whose distribution model no longer relies on MS Store nor Windows application packages). The problem is: when Landscape sends a message to install an instance, we execute `wsl --install` if that's a stock Ubuntu release. That used to install an APPX, so we'd later run the distro launcher to provision the new instance. But now, `wsl --install Ubuntu` or `wsl --install Ubuntu-24.04` would install the modern, tar-based, distro, which no …

feat(windows-agent): Landscape executor to install modern distros

---

CONTRIBUTING.md
README.md

Updates contributing guidelines:
* better clarity on source of code (two repos) and docs (one repo) for Ubuntu distro and Pro application
* updates links to repos and docs
* adds detail on testing docs locally and in PRs
* adds section on Open Docs Academy (WSL is a participating project)
NOTE: `CONTRIBUTING.md` is trancluded to `howto/contributing` in the docs.
NOTE: I will probably need to do a small, separate PR for the other repo (pointing to the docs here, etc.)
UPDATE (link to PR in other repo): https://github.com/ubuntu/WSL/pull/515
UDENG-6052

docs: Update contributor guidelines

---

.github/workflows/qa-azure.yaml
wsl-pro-service/internal/daemon/daemon.go
wsl-pro-service/internal/daemon/daemon_test.go
wsl-pro-service/internal/system/landscape.go
wsl-pro-service/internal/system/system.go
wsl-pro-service/services/wsl-pro.service

With the current behaviour wsl-pro-service and cloud-init race for the Landscape client.conf file during first boot.
It's possible that wsl-pro-service passes by the routine supposed to fix that configuration file before it exists, thus the instance wouldn't be registered with Landscape before a reboot.
We cannot simply order them via the systemd units because the Landscape configuration happens in cloud-init's final stage. The sync point for that stage is cloud-init.target. But that systemd target `Wants=multi-user.target` so it won't be reached before the login finishes. `wsl-pro.service`on the other hand declares itself as  `WantedBy=multi-user.target` so it has a systemd target against which it's installed (otherwise it wouldn't be enabled), which makes it a dependency for the boot, …

fix(wsl-pro-service): wait for cloud-init before fixing Landscape client.conf

---

SECURITY.md

I got a bit surprised to notice that we're not linking to a specific security policy in this repository when referring to this topic internally.
So I took the contents of ubuntu/WSL's SECURITY.md and adjusted slightly to be specific to this repository meanwhile both repositories exist for distinct purposes.

fix: Adapts the ubuntu/WSL SECURITY.md contents for this repository

---

docs/.custom_wordlist.txt
docs/explanation/binfmt.md
docs/explanation/index.md

While https://github.com/ubuntu/WSL/issues/512 is a representative issue, I've seen similar complains in the upstream repository about binfmt_misc registration mediated by systemd not working. I've also seen a bunch of other complains in the past about WSL binary interoperability not working because of some surprising interaction with `systemd-binfmt.service`.
This explanation page aims to eliminate (or at least decrease the amount of) surprises by:
- Explaining power users why we chose to disable that service
- Giving them knowledge to do the opposite and deal with potential consequences
I have high hopes (based on conversations I already had with upstream) that we'll see strong improvements in this area still in the WSL 2.5.x release series.
---
UDENG-6366

feat(docs): Explanation about binfmt and Ubuntu specifics

---

docs/.custom_wordlist.txt
docs/explanation/index.md
docs/explanation/security-overview.md
docs/howto/cloud-init.md
docs/howto/index-remote-deployment.md
docs/howto/install-ubuntu-wsl2.md
docs/reference/firewall_requirements.md
docs/tutorials/deployment.md
docs/tutorials/getting-started-with-up4w.md

Adds a new security overview page to the Explanation section of the docs.
This page outlines security consideration when using Ubuntu on WSL, includes links to relevant security information found elsewhere, and briefly mentions some tips for configuring features relevant to security.
In future, this could possibly be broken down into individual pages if some of the content was to be developed further, but for now a single page is sufficient.
UDENG-6389

docs: add a security overview

---

windows-agent/internal/distros/database/database.go
windows-agent/internal/distros/database/database_test.go
windows-agent/internal/proservices/landscape/executor.go
windows-agent/internal/proservices/landscape/executor_test.go
windows-agent/internal/proservices/proservices.go

If a distro is invalidated (the user deletes it, for example), its cloud-init files may stick around without being cleaned up. This could lead to unwanted behavior if a new distro with the same name is created.
Also, if a Landscape install falls, the corresponding cloud-init file is not cleaned up. This fixes that as well.
---
UDENG-6343

fix(windows-agent): Cleanup cloud init files for invalid distros

---

wsl-pro-service/internal/daemon/daemon.go
wsl-pro-service/internal/daemon/daemon_test.go
wsl-pro-service/internal/daemon/export_test.go
wsl-pro-service/services/wsl-pro.service

The current implementation of wsl-pro-service's `daemon.Serve()` keeps trying to connect to the Windows agent indefinitely, with exponential back-off starting at 1 second and saturating at 60 min with a power of 2 growth factor. That means it will roughly take 2 minutes to saturate the back-off wait time and then keep retrying at every minute. Since most WSL users don't have the Windows agent running, that means one log line being added to the journal by default every minute. That's not a good default.
With this PR I aim to make wsl-pro-service quit gracefully after a predefined number of consecutive retry attempts to connect to the Windows agent. Since systemd is set to restart it always, I'm changing the restart interval from 2 seconds to 20 minutes. So we'd be trying to connect to the …

fix(wsl-pro-service): Less logging

---

docs/.wordlist.txt
docs/howto/backup-and-restore.md
docs/howto/cloud-init.md
docs/howto/install-ubuntu-wsl2.md
docs/howto/verify-subscribe-attach.md
docs/reference/distributions.md
docs/tutorials/develop-with-ubuntu-wsl.md

Updates the documentation to include WSL's new distribution format and recommend different wsl commands for common tasks.
* Defaulting to `wsl -d <Distro>` to run instances instead of `<Distro>.exe`
* Referencing use of `wsl ~` to start a distro in Ubuntu home dir, as opening in mounted C drive could be unexpected for users
* Changing to `wsl --install <Distro>` instead of `wsl --install -d <Distro>`
* Adding section on tar-based Ubuntu distros to install guide
* Adding explanatory notes on new distro format in relevant pages
As we are still in a transitionary phase between the old and new formats, we shouldn't remove information on the old format yet; for example, the reference page on Ubuntu distributions still talks about the AppxPackage, etc. There, I added an explanatory note about …

docs: new distro format

---

wsl-pro-service/debian/rules

Using golang build package system is not enough, we need to ensure that golang debhelper is hooked in too to populate that field.

fix: Ensure Built-Using is populated

---

.github/actions/build-msix/action.yml
.github/workflows/publish-msix.yaml
msix/UbuntuProForWSL/Package.appxmanifest
msix/UbuntuProForWSL/UbuntuProForWSL.appinstaller
msix/UbuntuProForWSL/UbuntuProForWSL.wapproj

Spec WS044 and its backing proof of concept details the work being done here. Essentially we aim to provide an alternative to MS Store when distributing this application with some integration with the OS at least for automatic updates. Windows provides this feature via the App Installer file. This PR defines the app installer file for UP4W that assumes the MSIX packages will remain stored as GH release assets. Different from the PoC here we care about the packaging having a trusted signature, thus we cannot immediately publish it, instead the GH release automatically created by CI remains in draft until we acquire and upload the signed version and edit the release draft manually.
The targeted Windows versions are also changed, keeping consistency between the multiple places where we refer …

feat(msix): Integrates the App installer file

---

docs/.custom_wordlist.txt
docs/index.md
docs/reference/distributions.md
docs/reference/index.md
docs/reference/release_notes.md

Adds a release notes page to the Reference section of the docs.
Goals:
* Have a single place to find Ubuntu-on-WSL-specific release notes
* Emphasise the latest supported versions of the distro and the Windows app
* Focus on highlights (this is not a changelog)
* Include notes for older LTS releases and interim releases in optional, dropdown sections
UDENG-7637

docs: add release notes page

---

docs/.custom_wordlist.txt
docs/explanation/compare-wsl-versions.md
docs/explanation/index.md

This PR adds a new page to the documentation on the differences between the major versions of WSL and how these differences affect Ubuntu for WSL and Ubuntu Pro for WSL.
A quick summary table as well as more detailed explanations are included on the page. Links to relevant pages of the documentation, both internal and external, are included.
The titles and internal page names are version agnostic just in case there is ever a WSL 3. If that ever is the case, then we can expand on this page without needing to change links or titles.
---
[UDENG-7644](https://warthogs.atlassian.net/browse/UDENG-7644)
[UDENG-7644]: https://warthogs.atlassian.net/browse/UDENG-7644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: add comparison of WSL versions and their impact on Ubuntu

---

docs/tutorials/getting-started-with-up4w.md

Certain .wslconfig entries may break the communication between the Windows agent and the WSL pro service inside the instances. As we don't know the future to list them all and how they could break it, I just made a generic short line about this theme making things simple.
UDENG-7640

fix(docs): Clarify why removing .wslconfig in the UP4W tutorial

---

docs/howto/set-up-landscape-client.md

It has to be a Fully Qualified Domain Name. Submitting complete URLs break communication attempts in many ways. Those errors were mostly silent, specially when the user submitted the config via the Advanced configuration option (where they crafted the config by hand).
An effort is being made in #1285 to present those errors to the UI, but that's still not enough.
UDENG-7545

fix(docs): More emphasis about Landscape FQDN

---

.github/actions/build-msix/action.yml
tools/build/build-appx.ps1
tools/build/compute_version.go

This way we avoid subprocessing it three times in build-msix action. The usage in debian/prepare-source.sh didn't change.
We didn't have to do this now, but I need something else on top of main to issue a new tag to test the autoupdates end-to-end.
---
UDENG-7812

fix(tools): compute_version now outputs json

---

.github/actions/build-msix/action.yml

And renames it to releaseType in consistency with other places we use similar names for the same purpose.
The latest run of that publish-msix action attempted to create a stable release because that output variable was not correct.

fix(CI): build-msix output variable

---

docs/howto/install-ubuntu-wsl2.md
docs/tutorials/develop-with-ubuntu-wsl.md

Removed mentions of "Open Powershell as an Administrator" in Ubuntu WSL installation guides, and replaced surrounding text with more accurate and descriptive instructions.
Addresses the following issue: https://github.com/canonical/open-documentation-academy/issues/282

docs: Fixed open Powershell as admin instructions in WSL installation guide

---

docs/explanation/compare-wsl-versions.md
docs/explanation/security-overview.md
docs/howto/cloud-init.md
docs/howto/custom-ubuntu-distro.md
docs/howto/gpu-cuda.md
docs/howto/install-ubuntu-wsl2.md
docs/reference/release_notes.md
docs/tutorials/develop-with-ubuntu-wsl.md
docs/tutorials/getting-started-with-up4w.md

* Uses the convention of having a space between WSL and `<version number>`, e.g., "WSL 2", which is more common than "WSL2"
* Adds notes to tutorials and guides emphasising that WSL 2 is required
* Links added to new WSL versions explanation where appropriate
UDENG-7253

docs: clarifications relating to WSL versions

---

agentapi/dart/lib/src/agentapi.pb.dart
gui/packages/p4w_ms_store/windows/CMakeLists.txt
msix/UbuntuProForWSL/Package.appxmanifest
msix/UbuntuProForWSL/UbuntuProForWSL.wapproj
msix/agent/agent.vcxproj
msix/storeapi/storeapi.vcxproj
storeapi/base/Exception.hpp
storeapi/test/CMakeLists.txt

The Windows 2025 GH runner no longer ships the SDK version 22621, instead it only comes with the version 26100.
While upgrading the SDK is usually advised and MS most often handles backwards compatibility, the runner image coming only with that version requires us to adjust a few things in the project:
- First: the target version/max version tested in the MSBuild files must be updated matching that SDK version
- The `storeapi.dll` project file needs to link explicitly against `runtimeobject.lib`. I couldn't find a public explanation for that or changelog entry, but noticed that pattern in the [cppwinrt tests](https://github.com/microsoft/cppwinrt/blob/34fba98b48cc4cf98e069f7f2c1f7f51122894cf/test/test/CMakeLists.txt#L59) as well as a Flutter plugin for Windows [CMake …

maint: Cope with Windows SDK and Dart protoc plugin upgrades

---

common/testutils/testutils.go
end-to-end/go.mod
end-to-end/go.sum
mocks/go.mod
mocks/go.sum
mocks/landscape/landscapemockservice/landscape_mock_service.go
tools/go.mod
tools/go.sum
windows-agent/go.mod
windows-agent/go.sum
windows-agent/internal/distros/database/database_test.go
windows-agent/internal/distros/database/export_test.go
windows-agent/internal/distros/database/testdata/TestDatabaseGetUnmanaged/other-os-release
windows-agent/internal/distros/database/testdata/TestDatabaseGetUnmanaged/ubuntu-os-release
windows-agent/internal/distros/database/unmanaged.go
windows-agent/internal/proservices/landscape/executor.go
windows-agent/internal/proservices/landscape/landscape_test.go
windows-agent/internal/proservices/landscape/testdata/TestSendUpdatedInfo/ubuntu-os-release
windows-agent/internal/proservices/landscape/utils.go

The spec WS043 deals with augmenting the Windows agent to report to the Landscape server about WSL instances not managed by this system. In that spec we restricted the information to only touch Ubuntu instances. Landscape's ultimate objective is to eventually send commands to remove such instances if the system administrator desires.
This PR implements a method in the agent's database to report the instances considered unmanaged (Ubuntu instances that didn't present themselves to the agent - what is done by the wsl-pro-service), which is later added to the hostagent info message the agent eventually sends to the server. The Landscape hostagent API dependency is updated to include that field. The list of unmanaged instances is a best effort snapshot, we don't cache that data for later …

feat(windows-agent): Report unmanaged instances to the Landscape server
