canonical/ubuntu-pro-for-wsl

- wsl-pro-service/debian/copyright
I hated every second I was doing this.
---
UDENG-2213
> maint(wsl-pro-service): Add vendored dependency copyright notices

- wsl-pro-service/debian/changelog
> maint: release wsl-pro-service 0.1 to noble

- wsl-pro-service/debian/control
- wsl-pro-service/debian/copyright
- wsl-pro-service/debian/tests/control
> fix(wsl-pro-service): Fix debian issues and warnings

- .github/actions/flutter-qa/action.yaml
- .github/workflows/qa.yaml
- gui/packages/p4w_ms_store/test/p4w_ms_store_test.dart
- gui/packages/ubuntupro/lib/core/base58_check.dart
- gui/packages/ubuntupro/lib/pages/startup/startup_page.dart
- gui/packages/ubuntupro/lib/pages/subscription_status/subscribe_now_page.dart
- gui/packages/ubuntupro/test/core/base58_check_test.dart
- gui/packages/ubuntupro/test/core/environment_test.dart
- gui/packages/ubuntupro/test/pages/subscription_status/subscribe_now_page_test.dart
- gui/packages/ubuntupro/test/pages/subscription_status/subscribe_now_widgets_test.dart
- gui/packages/ubuntupro/test/startup/startup_page_test.dart
And pick some low-hanging fruits to make it look better :p
The enum tests and exceptions were a pretty good point, though, as the added tests makes the l10n more future proof.
Closes UDENG-271
> ci: Report test coverage of the Flutter side of the project

- README.md
> docs: Fix readme badges

- .github/workflows/qa.yaml
codecov v4 action requires now a token.
UDENG-2246
> maint(ci): inject token to report coverage with v4

- gui/packages/ubuntupro/assets/Ubuntu-tag.svg
- gui/packages/ubuntupro/lib/app.dart
- gui/packages/ubuntupro/lib/pages/subscription_status/subscribe_now_page.dart
- gui/packages/ubuntupro/lib/pages/widgets/page_widgets.dart
- gui/packages/ubuntupro/pubspec.lock
- gui/packages/ubuntupro/pubspec.yaml
- Added SVG logo as parameter
- Squared button corners and adjusted styles
- Added additional padding between elements
*Force push was to correct signing*
---
UDENG-1784
> maint(gui-ubuntupro): Update subscribe now page to proposed styles

- docs/howto/pro-attach.md
I think `LandscapeConfig` is an error
> docs: Update Ubuntu Pro token value name

- docs/.gitignore
- docs/build_requirements.py
> dix(docs): Fix broken path in doc metadata

- docs/dev/howto/06-access-the-logs.md
- windows-agent/cmd/ubuntu-pro-agent/agent/agent.go
- windows-agent/cmd/ubuntu-pro-agent/agent/agent_test.go
- windows-agent/cmd/ubuntu-pro-agent/main.go
- windows-agent/cmd/ubuntu-pro-agent/main_test.go
- windows-agent/internal/distros/database/database.go
- windows-agent/internal/distros/database/database_test.go
- windows-agent/internal/distros/distro/distro.go
- windows-agent/internal/distros/distro/distro_test.go
- wsl-pro-service/cmd/wsl-pro-service/main.go
Two-fold pull request:
- Windows Agent:
- The logs are moved to the public directory @ $HOME/.ubuntupro/log
- The logs print the version
- WSL Pro Service:
- The logs print the version
> feat(logging): Make logs public and print version

- windows-agent/internal/proservices/landscape/distroinstall/distroinstall_windows.go
- wsl-pro-service/debian/rules
Also sneak in the wsl-pro-service build fix
> fix(windows-agent): Fix launcher flags when installing a distro

- windows-agent/internal/proservices/registrywatcher/registry/registry_windows.go
> feat(windows-agent): The agent creates the registry key if it does not exist

- windows-agent/internal/config/config.go
- windows-agent/internal/proservices/registrywatcher/registry/registry_mock.go
- windows-agent/internal/proservices/registrywatcher/watcher.go
- windows-agent/internal/proservices/registrywatcher/watcher_test.go
The rush and excitement of the upcoming beta made us cut some corners here and there. This PR fixes some of those corners before they cristalize.
> maint: Clean up pre-beta tech debt

- windows-agent/internal/proservices/landscape/connection.go
- windows-agent/internal/proservices/landscape/distroinstall/distroinstall_windows.go
- windows-agent/internal/proservices/landscape/service.go
Quick fixes of problems uncovered during today's testing team testing session
> fix(Landscape): Testing quick fixes

- docs/howto/set-up-up4w.md
This updates the docs to reflect changes in #613 and #620
> docs(windows-agent): Update registry instructions now that the key is auto-generated

- .github/dependabot.yml
> ci: run dependabot weekly on thursday

- .golangci.yaml
- common/grpc/contextidler/contextidler_test.go
- common/grpc/logconnections/logconnections.go
- common/grpc/logstreamer/caller.go
- common/testutils/set_test.go
- windows-agent/internal/daemon/networking_windows.go
- windows-agent/internal/distros/worker/task_queue.go
- windows-agent/internal/distros/worker/worker.go
- windows-agent/internal/distros/worker/worker_test.go
- wsl-pro-service/internal/testutils/mock_agent.go
> maint: Use new linters in golangci-lint

- wsl-pro-service/debian/changelog
If PR #732 get's done in time, we must add a matching line in the changelog. Otherwise, this is it.
> maint(wsl-pro-service): Prepare changelog for wsl-pro-service v0.1.3

- docs/tutorial/index.md
Fixes broken link for Landscape Server installation and configuration.
UDENG-3628
> docs: Fix broken link to Landscape install and config

- windows-agent/internal/proservices/landscape/executor.go
Well, the download function might now be doing more than it should.
But WSL imposes the precondition that nobody else holds the rootfs file open when registering the distro instance. So we must ensure the file is closed by the time we call import. This is the most readable way to do so IMHO.
We could have wrapped the file creation and the call to download in a closure. It would be more compliant to SRP, but less readable.
---
UDENG-3590
> fix(agent): Create the rootfs tarball in the download function

- docs/howto/06-access-the-logs.md
I think this is a typo. I don't actually have UP4W set up so I can't verify, but pretty sure. (Just passing by)
> docs: Fix typo

- .github/actions/build-msix/action.yml
These were leading to a dirty git history, which made the version in the Flutter app show as "dirty"
> ci: Delete certificate files after importing

- README.md
I wish I could have not seen this
> maint(docs): Update README.md

- docs/.custom_wordlist.txt
- docs/howto/gpu-cuda.md
- Linked an external AMD documentation related to WSL.
- Updated the Further Resources section with an external link to CUDA on WSL User Guide
- Replaced the non-standard note blocks with [MySt-style note blocks](https://pradyunsg.me/furo/reference/admonitions/)
- consolidated into one section "What you will need" secton and "Prerequisites" section.
- Updated link named for "NVIDIA’s CUDA Post Installation Actions".
**Screenshots**
> docs: Fixes to GPU/NVIDIA guide
